import "./globals.css";
import { Inter, Old_Standard_TT } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const oldStandard = Old_Standard_TT({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-old-standard-tt",
});

export const metadata = {
  title: "Manifesto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-HOMEPAGE_BGCOLOR">
        <header className="bg-NAVBAR_COLOR text-white sticky top-0 z-10 content-center">
          <section className="max-w-4xl mx-auto p-4 flex justify-center">
            <h1 className="font-oldStandard">
              <a href="#hero">M</a>
            </h1>
          </section>
        </header>
      </body>
    </html>
  );
}
